### ISSUE TITLE
Intermittent failures when scanning

### ISSUE THREAD

**Issue by ljmf00** [anchore/scan-action#140]
This action often fails without errors after scanning a docker due to failing parse with `grype`. Please see my failing workflows [here](https://github.com/ljmf00/dotfiles/actions). (e.g. https://github.com/ljmf00/dotfiles/actions/runs/1738391162)

**Comment by kzantow** [comment]
Hi @ljmf00 There were a number of issues regarding SARIF output that have been addressed, I believe the failures you are seeing are related to this. Would you be able to try the latest version (3.2.1)?

**Comment by ljmf00** [comment]
I can confirm, it's working now. I'm going to check if intermittent heisenbugs still happen occasionally. If yes, I can reopen this.
